# Generated by Django 5.1.5 on 2025-01-29 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_eventos', '0002_remove_participacao_confirmado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='usuarios_removidos',
            field=models.ManyToManyField(blank=True, related_name='eventos_bloqueados', to=settings.AUTH_USER_MODEL),
        ),
    ]
